// <auto-generated />
using System;
using HomeVital.Repositories.dbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeVital.Repositories.Migrations
{
    [DbContext(typeof(HomeVitalDbContext))]
    [Migration("20250227111217_AddPatientIDAndWorkerIDToUser")]
    partial class AddPatientIDAndWorkerIDToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeVital.Models.Entities.BloodPressure", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("BodyPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Diastolic")
                        .HasColumnType("integer");

                    b.Property<string>("MeasureHand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MeasurementID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<int>("Pulse")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Systolic")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MeasurementID");

                    b.ToTable("BloodPressures");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.Bloodsugar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<float>("BloodsugarLevel")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MeasurementID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MeasurementID");

                    b.ToTable("Bloodsugars");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.BodyTemperature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MeasurementID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("MeasurementID");

                    b.ToTable("BodyTemperatures");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.BodyWeight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MeasurementID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("MeasurementID");

                    b.ToTable("BodyWeights");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.HealthcareWorker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("HealthcareWorkers");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.Measurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("HealthcareWorkerID")
                        .HasColumnType("integer");

                    b.Property<string>("Kennitala")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PatientID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Kennitala")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.BloodPressure", b =>
                {
                    b.HasOne("HomeVital.Models.Entities.Measurement", null)
                        .WithMany("BloodPressure")
                        .HasForeignKey("MeasurementID");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.Bloodsugar", b =>
                {
                    b.HasOne("HomeVital.Models.Entities.Measurement", null)
                        .WithMany("BloodSugar")
                        .HasForeignKey("MeasurementID");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.BodyTemperature", b =>
                {
                    b.HasOne("HomeVital.Models.Entities.Measurement", null)
                        .WithMany("BodyTemperature")
                        .HasForeignKey("MeasurementID");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.BodyWeight", b =>
                {
                    b.HasOne("HomeVital.Models.Entities.Measurement", null)
                        .WithMany("BodyWeight")
                        .HasForeignKey("MeasurementID");
                });

            modelBuilder.Entity("HomeVital.Models.Entities.Measurement", b =>
                {
                    b.Navigation("BloodPressure");

                    b.Navigation("BloodSugar");

                    b.Navigation("BodyTemperature");

                    b.Navigation("BodyWeight");
                });
#pragma warning restore 612, 618
        }
    }
}
