name: Build and deploy ASP.Net Core app to Azure Web App - HomeVital-API-DEV

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release  

      - name: dotnet publish
        run: |
          dotnet publish HomeVital.API/HomeVital.API.csproj -c Release -o ${{github.workspace}}/myapp  

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4  
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4 
        with:
          name: .net-app

      - name: Log in to Azure with Managed Identity
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY
      - name: Set Azure Web App Environment Variables (DEV)
        run: |
          az webapp config appsettings set --name homevital-api-dev --resource-group HomeVital_harmony --settings "ConnectionStrings__Default=${{ secrets.DEV_CONNECTION_STRING }}"
        shell: bash
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'homevital-api-dev'  
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEV }}