name: Run EF Core Migrations

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:  # Allow manual triggering

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Set database connection string
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            CONNECTION_STRING="${{ secrets.PROD_CONNECTION_STRING }}"
          else
            CONNECTION_STRING="${{ secrets.DEV_CONNECTION_STRING }}"
          fi
          
          # Ensure the string is stored correctly in the environment variable
          echo "DB_CONNECTION_STRING=$(echo "$CONNECTION_STRING" | tr -d '\n' | tr -d '\r')" >> $GITHUB_ENV
      
          # Debugging - Print the first 20 characters only (without exposing the secret)
          echo "Using connection string (masked): ${DB_CONNECTION_STRING:0:20}..."

      - name: Apply EF Core Migrations
        run: |
          cd HomeVital.API
          echo "Running migration with connection string (masked): ${DB_CONNECTION_STRING:0:20}..."
            
          # Ensure the connection string is passed correctly
          dotnet ef database update --connection "${DB_CONNECTION_STRING}" --project ../HomeVital.Repositories --startup-project .