name: Run EF Core Migrations

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:  # Allow manual triggering

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Set database connection string
        run: |
          echo "Checking branch: ${{ github.ref_name }}"
      
          # Ensure variable is assigned safely
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Using production connection string"
            echo "DB_CONNECTION_STRING=${{ secrets.PROD_CONNECTION_STRING }}" >> $GITHUB_ENV
          else
            echo "Using development connection string"
            echo "DB_CONNECTION_STRING=${{ secrets.DEV_CONNECTION_STRING }}" >> $GITHUB_ENV
          fi
      
          # Debugging - Print first 50 characters of the stored string
          echo "Stored connection string (masked): ${DB_CONNECTION_STRING:0:50}..."

      - name: Apply EF Core Migrations
        run: |
          cd HomeVital.API
          echo "Running migration with connection string (masked): ${DB_CONNECTION_STRING:0:50}..."
        
          # ✅ Escape semicolons to prevent errors
          CONNECTION_STRING_ESCAPED=$(echo "$DB_CONNECTION_STRING" | sed 's/;/\\;/g')
        
          # Debug: Print escaped connection string
          echo "Escaped Connection String (First 50 chars): ${CONNECTION_STRING_ESCAPED:0:50}"
        
          # ✅ Use the escaped connection string safely
          dotnet ef database update --connection "$CONNECTION_STRING_ESCAPED" --project ../HomeVital.Repositories --startup-project .